export const MAPA_BANDEIRAS: Record<string, string> = {
  brasil: 'br',
  argentina: 'ar',
  uruguai: 'uy',
  paraguai: 'py',
  chile: 'cl',
  colômbia: 'co',
  colombia: 'co',
  peru: 'pe',
  venezuela: 've',
  equador: 'ec',
  bolívia: 'bo',
  bolivia: 'bo',
  'estados unidos': 'us',
  eua: 'us',
  usa: 'us',
  canadá: 'ca',
  canada: 'ca',
  méxico: 'mx',
  mexico: 'mx',
  cuba: 'cu',
  alemanha: 'de',
  itália: 'it',
  italia: 'it',
  portugal: 'pt',
  espanha: 'es',
  frança: 'fr',
  franca: 'fr',
  'reino unido': 'gb',
  inglaterra: 'gb',
  bélgica: 'be',
  belgica: 'be',
  'países baixos': 'nl',
  holanda: 'nl',
  irlanda: 'ie',
  escócia: 'gb-sct',
  'república tcheca': 'cz',
  'republica tcheca': 'cz',
  polônia: 'pl',
  polonia: 'pl',
  suíça: 'ch',
  suica: 'ch',
  áustria: 'at',
  austria: 'at',
  dinamarca: 'dk',
  suécia: 'se',
  suecia: 'se',
  noruega: 'no',
  grécia: 'gr',
  grecia: 'gr',
  japão: 'jp',
  japao: 'jp',
  china: 'cn',
  'coreia do sul': 'kr',
  austrália: 'au',
  australia: 'au',
  'nova zelândia': 'nz',
  'nova zelandia': 'nz',
  'áfrica do sul': 'za',
  'africa do sul': 'za',
  egito: 'eg',
  marrocos: 'ma',
}

export function bandeiraUrl(pais: string | null | undefined): string | null {
  const nomePais = pais?.toLowerCase().trim() || ''
  const codigoIso = MAPA_BANDEIRAS[nomePais] || null
  return codigoIso ? `https://flagcdn.com/w20/${codigoIso}.png` : null
}
